name: Promote App

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          check-latest: false
          update-environment: true
          allow-prereleases: false

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 PyGithub

      - name: Promote App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/promote_app.py
