name: Merge SOAR-Apps → Main

on:
  push:
    branches:
      - soar_apps
    paths:
      - 'apps/**/*.tgz'

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # so we can create a PR

    steps:
      - name: Check out soar_apps
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # need full history to compare

      - name: Detect newest app
        id: detect
        run: |
          app=$(python scripts/get_new_app.py "apps/**/*.tgz")
          echo "app_name=$app" >> $GITHUB_OUTPUT

      - name: Open (or update) PR to merge into main
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const app = '${{ steps.detect.outputs.app_name }}';
            const base = 'main';
            const head = 'soar_apps';

            // First, see if a PR already exists from soar_apps → main:
            const { data: existing } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${head}`,
              base,
              state: 'open'
            });

            if (existing.length) {
              console.log(`PR already open: #${existing[0].number} ${existing[0].html_url}`);
            } else {
              const pr = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head,
                base,
                title: `Add SOAR app ${app}`,
                body: `Bringing the new SOAR app **${app}** from \`${head}\` into \`${base}\` for review/QA.`
              });
              console.log(`PR created: ${pr.data.html_url}`);
            }
