name: Promote SOAR App to Ready for Prod

on:
  push:
    branches:
      - main
    paths:
      - 'apps/*.tgz'

jobs:
  promote_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to create PRs and switch branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Promote Script
        run: python scripts/promote_app.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
